version: "3"

env:
  tag_version: v1.6.10
  DOCKER_HOST: ssh://root@darklab:22

tasks:
  build-version:
    cmds:
      - autogit version > app/settings/version.txt || echo 'not installed autogit' > settings/version.txt

  build:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -v -o main main.go

  test:
    cmds:
      # - go clean -cache ./...
      # - go clean -testcache ./...
      # -count=1
      - go test ./... -coverprofile=cover.out {{.CLI_ARGS}}
    env:
      AUTOGIT_PROJECT_FOLDER:
        sh: echo "$(pwd)"

  test:cover:
    cmds:
      - go tool cover -html=cover.out

  test:cover:total:
    cmds:
      - task: test
      - go tool cover -func cover.out

  doc-web:
    cmds:
      - godoc -http=:6060

  docker:ps:
    cmds:
      - docker ps

  docker:build:
    cmds:
      - docker build --tag darkwind8/darkbot:$tag_version .

  docker:push:
    cmds:
      - docker push darkwind8/darkbot:$tag_version

  docker:run:
    cmds:
      - docker run -it darkwind8/darkbot:$tag_version

  docker:buildpush:
    cmds:
      - task: docker:build
      - task: docker:push

  shell:staging:
    cmds:
      - ssh -i ~/.ssh/id_rsa.darklab root@5.161.80.45

  shell:production:
    cmds:
      - ssh -i ~/.ssh/id_rsa.darklab root@5.161.54.150

  copy_prod_to_stag:
    cmds:
      - scp -i ~/.ssh/id_rsa.darklab root@5.161.179.34:/var/lib/darklab/darkbot/prod.sqlite3 root@5.161.80.45:/var/lib/darklab/darkbot
      - scp -i ~/.ssh/id_rsa.darklab root@5.161.179.34:/var/lib/darklab/darkbot/prod.sqlite3-shm root@5.161.80.45:/var/lib/darklab/darkbot
      - scp -i ~/.ssh/id_rsa.darklab root@5.161.179.34:/var/lib/darklab/darkbot/prod.sqlite3-wal root@5.161.80.45:/var/lib/darklab/darkbot

  copy_prod_to_local:
    cmds:
      - scp -i ~/.ssh/id_rsa.darklab root@5.161.179.34:/var/lib/darklab/darkbot/prod.sqlite3 ./data
      - scp -i ~/.ssh/id_rsa.darklab root@5.161.179.34:/var/lib/darklab/darkbot/prod.sqlite3-shm ./data
      - scp -i ~/.ssh/id_rsa.darklab root@5.161.179.34:/var/lib/darklab/darkbot/prod.sqlite3-wal ./data

  copy_local_to_prod:
    cmds:
      - scp -i ~/.ssh/id_rsa.darklab ./data/prod.sqlite3 root@5.161.54.150:/var/lib/darklab/darkbot/
      - scp -i ~/.ssh/id_rsa.darklab ./data/prod.sqlite3-shm root@5.161.54.150:/var/lib/darklab/darkbot/
      - scp -i ~/.ssh/id_rsa.darklab ./data/prod.sqlite3-wal root@5.161.54.150:/var/lib/darklab/darkbot/

  venv:create:
    cmds:
      - python3 -m venv .venv
    status:
      - test -d .venv

  venv:install:
    cmds:
      - .venv/bin/pip install -r requirements.txt -c constraints.txt
    status:
      - test -f .venv/bin/mkdocs

  mkdocs:dev:
    cmds:
      - task: venv:install
      - .venv/bin/mkdocs serve

  backup: # /var/lib/darklab/prod/darkbot
    cmds: # ssh -i ~/.ssh/id_rsa.darklab root@5.161.179.34
      - echo "TODO write command for backup"

  profile:run:
    cmds:
      - go run . run

  profile:render:
    cmds:
      - curl http://localhost:8080/debug/pprof/heap > heap.{{.DATE}}.pprof
      - go tool pprof --pdf ~/repos/pet_projects/fl-darkbot/main heap.{{.DATE}}.pprof > file_{{.DATE}}.pdf
      - rm heap.{{.DATE}}.pprof
    vars:
      DATE:
        sh: date +%s

  profile:render2:
    cmds:
      - curl http://localhost:8080/debug/pprof/heap > heap.{{.DATE}}.pprof
      - go tool pprof --base heap.1675610376.pprof --pdf ~/repos/pet_projects/fl-darkbot/main heap.{{.DATE}}.pprof > file_diff_{{.DATE}}.pdf
      - rm heap.{{.DATE}}.pprof
    vars:
      DATE:
        sh: date +%s

  profile:render3:
    cmds:
      - task: profile:render
      - task: profile:render2
