"""0000

Revision ID: db3ba0925894
Revises: 459fcafdfdfb
Create Date: 2022-08-27 19:15:10.384852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3ba0925894'
down_revision = '459fcafdfdfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag', 'channel_id', name='_tag_channel_id_uc')
    )
    op.create_index(op.f('ix_base_id'), 'base', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_base_id'), table_name='base')
    op.drop_table('base')
    # ### end Alembic commands ###
