"""0000

Revision ID: c70f2bee5cad
Revises: 
Create Date: 2022-08-28 16:56:16.527304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70f2bee5cad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_id'), 'channel', ['id'], unique=False)
    op.create_table('base',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag', 'channel_id', name='_tag_channel_id_uc')
    )
    op.create_index(op.f('ix_base_id'), 'base', ['id'], unique=False)
    op.create_table('owner',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'channel_id', name='_owner_channel_uc')
    )
    op.create_index(op.f('ix_owner_id'), 'owner', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_owner_id'), table_name='owner')
    op.drop_table('owner')
    op.drop_index(op.f('ix_base_id'), table_name='base')
    op.drop_table('base')
    op.drop_index(op.f('ix_channel_id'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
