"""0000

Revision ID: 459fcafdfdfb
Revises: 480e9796df79
Create Date: 2022-08-27 13:57:41.873808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459fcafdfdfb'
down_revision = '480e9796df79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('name', sa.String(), nullable=True))
    op.add_column('owner', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('_owner_channel_uc', 'owner', ['id', 'channel_id'])
    op.drop_constraint('owner_channel_fkey', 'owner', type_='foreignkey')
    op.create_foreign_key(None, 'owner', 'channel', ['channel_id'], ['id'])
    op.drop_column('owner', 'channel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('channel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'owner', type_='foreignkey')
    op.create_foreign_key('owner_channel_fkey', 'owner', 'channel', ['channel'], ['id'])
    op.drop_constraint('_owner_channel_uc', 'owner', type_='unique')
    op.drop_column('owner', 'channel_id')
    op.drop_column('owner', 'name')
    # ### end Alembic commands ###
