"""0000

Revision ID: 480e9796df79
Revises: 
Create Date: 2022-08-21 16:34:57.123796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480e9796df79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_id'), 'channel', ['id'], unique=False)
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_id'), 'owner', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_owner_id'), table_name='owner')
    op.drop_table('owner')
    op.drop_index(op.f('ix_channel_id'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
