"""second

Revision ID: cb7d5a8c4cfd
Revises: 7d96510c73bc
Create Date: 2022-07-24 21:18:51.212256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7d5a8c4cfd'
down_revision = '7d96510c73bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('region', sa.String(), nullable=True))
    op.add_column('players', sa.Column('system', sa.String(), nullable=True))
    op.add_column('players', sa.Column('time', sa.String(), nullable=True))
    op.add_column('players', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('players', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('players', 'timestamp')
    op.drop_column('players', 'time')
    op.drop_column('players', 'system')
    op.drop_column('players', 'region')
    op.drop_column('players', 'name')
    # ### end Alembic commands ###
