"""2

Revision ID: 51a2c552e6c3
Revises: cb7d5a8c4cfd
Create Date: 2022-08-07 05:16:09.202739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a2c552e6c3'
down_revision = 'cb7d5a8c4cfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('health', sa.Float(), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bases_id'), 'bases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bases_id'), table_name='bases')
    op.drop_table('bases')
    # ### end Alembic commands ###
