"""0003

Revision ID: d6b845375f36
Revises: 51a2c552e6c3
Create Date: 2022-08-21 05:28:12.164922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b845375f36'
down_revision = '51a2c552e6c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bases_name'), 'bases', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bases_name'), table_name='bases')
    # ### end Alembic commands ###
