{
 "title": "App Darkbot",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Darkbot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by(guild_name) (darkbot_guilds_channels_gauge))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active channels across all guilds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by(guild_name) (darkbot_guilds_channels_gauge))\n- count(sum by(channel_id) (increase(darkbot_viewer_requests_count{error!=\"\"}[10m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deactivated Channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(channel_id) (increase(darkbot_viewer_requests_count{error!=\"\"}[10m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active guilds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(guild_name) (darkbot_guilds_channels_gauge))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active channels per guild",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(guild_name) (darkbot_guilds_channels_gauge)",
     "legendFormat": "some_user"
    }
   ]
  },
  {
   "title": "Active guilds",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(guild_name) (darkbot_guilds_channels_gauge{guild_name!=\"unknown\"})",
     "legendFormat": "guild"
    }
   ]
  },
  {
   "title": "Viewer Requests Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(guild_name) (increase(darkbot_viewer_requests_count{error=\"\"}[5m]))",
     "legendFormat": "some_guild"
    }
   ]
  },
  {
   "title": "Viewer Requests Errors [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by(channel_id, error) (increase(darkbot_viewer_requests_count{error!=\"\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "darkbot_uptime_seconds{error=\"\"}",
     "legendFormat": "{{guild_name}}"
    }
   ]
  },
  {
   "title": "Listener Requests Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum by(guild_name) (darkbot_listener_allowed_requests_count{error=\"\"})",
     "legendFormat": "some_guild"
    }
   ]
  },
  {
   "title": "Listener Kind of Operations [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by(command) (darkbot_listener_kind_operation{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Listener Requests Errors [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by(guild_name, error) (increase(darkbot_listener_allowed_requests_count{error!=\"\"}[10m]))",
     "legendFormat": "some_guild"
    }
   ]
  }
 ]
}